dist: trusty
language: minimal
before_install:
  - sudo add-apt-repository ppa:openscad/releases -y
  - sudo apt-get update -q
  - sudo apt-get install openscad -y
script:
  - sh ./scripts/generate-all.sh
