dist: trusty
language: minimal
before_install:
  - sudo add-apt-repository ppa:openscad/releases -y
  - sudo apt-get update -q
  - sudo apt-get install openscad xvfb mesa-utils libgl1-mesa-glx -y
script:
  - xvfb-run -s "-screen 0 1280x1024x24" sh ./scripts/generate-all.sh
deploy:
  provider: releases
  api_key:
    secure: "XIJQJYEKYjLuRM+/aFojNva5NOsQ9RSyK22l9vulN3sB2tSCkd03djrdUyq3DW3QR4i5zAewALMwZilClASWg4k2fNPrMK/wEEO1TvScctTqcc7ysVG2HxJr2dM73/c87rW9XotUmub5f3jms/EJcBZLGwvLjBn/QLyc6XTnwXkJQN+NLs0X5aa9tUgitOmoP869y5WeYCirBXv7i9aXUBOMCbprotah1VcObMFwsbtRnL26xwrfgRFEM0RVfM9Z3LyozTqbfHxcawG4uQ1idGA5iJOLdIzfB67QuHnI6fHfI80iUqviEuyDO8gxtLTiOSy5rYE84/3HSzkfH/OLZm3HjPYP0qz/AMKIONB3m5mhNOBryUxtgjVmIOxR5xth6vPQ1UsQ9zZaYcT95xNrOrQyaacVN5zrq6hx2FShZIOT6RQOW6gmj+vT5hKzT7dOZxVDZelUOG6SUNAa/erno+GKqmy1Xx/P/XhdfG1HLYtw3VVK3mzY8UlTEeLk6i0/Lm9KHt3bi9H+yHINA4estKLwCHvuGSLxTH1h0UVFrcWACp4gziJK0AAMRFhziG+H34VZxxPrunwuvvFXMJgSE/9dOENTC4lczuOazmHFce3u/3E9WDFdu+GDgur2kzhOlP0I/TSQ+lMxAEzPGh9RCZlJr3vVXmfmnI5h2493kb4="
  file_glob: true
  file:
    - models/**/*.png
    - models/**/*.stl
  skip_cleanup: true
  on:
    branch: master
